apiVersion: v1
kind: Service
metadata:
  name: postgres_service
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 33001
    name: postgres
  selector:
    app: postgres